[package]
name = "metagetta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-display-derive = "0.1.1"
regex = "1.6.0"
scraper = "0.13.0"
ureq = "2.5.0"
